### ISSUE TITLE
driver not workie work

### ISSUE THREAD

**Issue by zer0gra** [paysonism/v2-payson-ioctl-cheat-driver#2]
sir, i would appriciate it if you spent the time to fix your open source "ioctl driver" so i can use it. thanks

**Comment by blitzcheat** [comment]
> sir, i would appriciate it if you spent the time to fix your open source "ioctl driver" so i can use it. thanks

LOLLLL its easy its basic IOCTL driver and you add the CR3
CR3 copy paste from here : https://github.com/xetzzy/Fortnite-External-Source/blob/main/km/utils.hpp#L96

paysonism its not real dev only paster and sell shiit detected don't trust im

**Comment by zer0gra** [comment]
> > sir, i would appriciate it if you spent the time to fix your open source "ioctl driver" so i can use it. thanks
> 
> LOLLLL its easy its basic IOCTL driver and you add the CR3 CR3 copy paste from here : https://github.com/xetzzy/Fortnite-External-Source/blob/main/km/utils.hpp#L96
> 
> paysonism its not real dev only paster and sell shiit detected don't trust im he teams up with "Skar" 2 big scammer / Paster / which puts rats/trojan in your PC

1 he doesnt rat 
2 it was i joke im a dev myself ;)

**Comment by paysonism** [comment]
nigga skar hates me he tried ratting me like 5 times 😭

**Comment by paysonism** [comment]
wtf is this mf on about
